project_id = "equruhaugrbtqjixqgtg"

[functions.ai-engine]
verify_jwt = false

[functions.webhook-router]
verify_jwt = false

[functions.process-voice-agent-queue]
verify_jwt = false

[functions.plivo-callback]
verify_jwt = false

[functions.plivo-answer]
verify_jwt = false

[functions.plivo-ai-response]
verify_jwt = false
