project_id = "equruhaugrbtqjixqgtg"

[functions.ai-engine]
verify_jwt = false

[functions.webhook-router]
verify_jwt = false

[functions.process-voice-agent-queue]
verify_jwt = false

[functions.plivo-callback]
verify_jwt = false

[functions.plivo-answer]
verify_jwt = false

[functions.plivo-ai-response]
verify_jwt = false

[functions.xero-sync]
verify_jwt = false

[functions.ai-finance-forecast]
verify_jwt = false

[functions.inbound-email]
verify_jwt = false

[functions.whatsapp-send-message]
verify_jwt = false

[functions.whatsapp-incoming-webhook]
verify_jwt = false

[functions.whatsapp-automation]
verify_jwt = false

[functions.ai-chatbot]
verify_jwt = false

[functions.job-notifications]
verify_jwt = false

[functions.ai-report-generator]
verify_jwt = false
